// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// linear_regression
Rcpp::List linear_regression(Eigen::MatrixXd data);
RcppExport SEXP _regressionCpp_linear_regression(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(linear_regression(data));
    return rcpp_result_gen;
END_RCPP
}
// logistic_regression
Rcpp::List logistic_regression(Eigen::MatrixXd data);
RcppExport SEXP _regressionCpp_logistic_regression(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(logistic_regression(data));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_regressionCpp_linear_regression", (DL_FUNC) &_regressionCpp_linear_regression, 1},
    {"_regressionCpp_logistic_regression", (DL_FUNC) &_regressionCpp_logistic_regression, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_regressionCpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
